package View;
import Controller.Controller;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : GUI.java
//  @ Date : 05.11.2012
//  @ Author : 
//
//




public class GUI {
	private Controller contoller;
}
